required = [
    "github.com/emicklei/go-restful",
    "github.com/onsi/ginkgo", # for test framework
    "github.com/onsi/gomega", # for test matchers
    "github.com/kubernetes-sigs/kubebuilder", # For tests
    "github.com/pusher/git-store",
    "k8s.io/client-go/plugin/pkg/client/auth/gcp", # for development against gcp
    "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
    "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
    "sigs.k8s.io/controller-runtime/pkg/client/config",
    "sigs.k8s.io/controller-runtime/pkg/controller",
    "sigs.k8s.io/controller-runtime/pkg/handler",
    "sigs.k8s.io/controller-runtime/pkg/manager",
    "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
    "sigs.k8s.io/controller-runtime/pkg/source",
    "sigs.k8s.io/testing_frameworks/integration", # for integration testing
    "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1",
]

[prune]
  go-tests = true

[[constraint]]
name="github.com/pusher/git-store"
version="v0.5.0"

[[override]]
name="gopkg.in/src-d/go-git.v4"
version="v4.8.1"

[[override]]
name="k8s.io/api"
version="kubernetes-1.12.3"

[[override]]
name="k8s.io/apiextensions-apiserver"
version="kubernetes-1.12.3"

[[override]]
name="k8s.io/apimachinery"
version="kubernetes-1.12.3"

[[override]]
name="k8s.io/client-go"
version="kubernetes-1.12.3"

[[override]]
name="k8s.io/kube-aggregator"
version="kubernetes-1.12.3"

[[override]]
name="sigs.k8s.io/controller-runtime"
version="v0.1.9"

[[override]]
name="sigs.k8s.io/controller-tools"
version="v0.1.8"

[[override]]
name="sigs.k8s.io/testing_frameworks"
version="v0.1.1"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"
